### ISSUE TITLE
Update "required" data columns

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/ae-timelines#12]
Update which columns are actually required at: https://github.com/RhoInc/ae-timelines/wiki/Data-Guidelines

**Comment by samussiah** [comment]
Implemented in v1.3.0:

* ASTDY
* AENDY
* USUBJID
* RFENDTC
** For Participant Status filter
* AESEQ
* AESEV
* AESER
* TERM_COL
** Verbatim term

Removed AEBODSYS and AEDECOD because those require coded adverse events.  They can still be included both as filters and in the detail listing.

**Comment by jwildfire** [comment]
👍  @brittsikora Do you think you could update the wiki with this information?

**Comment by brittsikora** [comment]
Since the wiki page above links to the configuration page, I understand that the "Required?" note should be no (or N) for AEBODSYS and AEDECOD, howeve AEDECOD isn't currently in the configuration table - could it be listed as something else?

I will add the following to the Custom Data Mappings table:
- REFENDTC
- AESER
- TERM_COL 
Can you please provide the settings variable and descriptions for these?


There are a few in the current table that you don't mention here - are they no longer required?
- AEREL
- AETERM

**Comment by samussiah** [comment]
Thanks Britt!  TERM_COL should be AETERM and please drop RFENDTC as we decided against requiring it [here](https://github.com/RhoInc/ae-timelines/issues/21).  AEREL is no longer required.

**Comment by brittsikora** [comment]
AETERM is described as preferred term in the table and as verbatim term in your description above - which do you prefer to use as the variable name in the table?

Any more info you want me to include for AESER besides its default name?

**Comment by samussiah** [comment]
It's "Reported Term".  AESER is "Serious Event".  See the [gist](http://bl.ocks.org/samussiah/fef8d319af053dd6f2b3f30cad884828).

**Comment by brittsikora** [comment]
I've updated the wiki with all of that information - let me know if you need anything else

**Comment by jwildfire** [comment]
I made a few edits as well. @samussiah Can you please do a [final QC](https://github.com/RhoInc/ae-timelines/wiki/Configuration#overview-chart---webcharts-settings) of this page before we finalize the release. I'm pretty sure some of the defaults that we listed there have changed.

**Comment by samussiah** [comment]
Done.

**Comment by jwildfire** [comment]
Will cover this in standard wiki updates prior to release.
